### PR TITLE
let setting element models from different places

### PR DESCRIPTION
**Pull request by Kml55**
Before creating form, Users may need attach data to form elements. So Users can set model of elements before FormController.addFormElementsToView call.

### CODE REVIEW

**Comment by dkharrat** [comment]
Thanks for your contribution!

I'm trying to understand why this change is needed. Can you provide an example of a use-case that requires this change? Why aren't you able to set the model on the FormController directly? Some code snippets would help too if you have an example.

**Comment by Kml55** [comment]
I wanted to set model value from form element. Below code works on asynTask's onpostexecute theoratically before or after formController.addFormElementsToView(container); call..

```
FormElementController selectionCont = new SelectionController(CreateRecordActivity.this, name,name, true, "Select", domains, true);
if(selectionCont.getModel()==null){
        selectionCont.setModel(formController.getModel());
 }
 selectionCont.getModel().setValue("create_attribute"+"_"+name,attribute);
```

But I was stuck to do model value settings over elementController not over formController.  My perspective to model concept may be wrong. I was thinking at first, each element has its own model data independent from its form model data.

**Comment by dkharrat** [comment]
Yes, the model is set at the FormController level, which is then passed to the individual elements to extract the values it needs. Does this approach work for you? Do you have a use-case where you'd like to set a different model for each element separately?

**Comment by dkharrat** [comment]
Also, you mentioned you wanted to add elements asynchronously. That should still work as long as the FormController is initialized properly and you also add them within the main thread.

**Pull request closed without merging**
